export const FETCH_GLOBAL_STATS = 'FETCH_GLOBAL_STATS';
export const FETCH_ALL_US_STATES_STATS = 'FETCH_ALL_US_STATES_STATS';
export const FETCH_TODAY_US_STATES_STATS = 'FETCH_TODAY_US_STATES_STATS';
export const FETCH_YESTERDAY_US_STATES_STATS = 'FETCH_YESTERDAY_US_STATES_STATS';
export const FETCH_ALL_COUNTRIES_STATS = 'FETCH_ALL_COUNTRIES_STATS';
